package template


type GoType struct {
	Type     string
	TypeName string
}

var Warning string = `
// DO NOT EDIT THIS FILE MANUALLY
// Generated by go generate
`

type GenerateImplAndTest struct {
	Impl     string
	Test     string
	FileName string
}

var NumericTypes []GoType = []GoType{
	{
		Type:     "uint",
		TypeName: "Uint",
	},
	{
		Type:     "uint8",
		TypeName: "Uint8",
	},
	{
		Type:     "uint16",
		TypeName: "Uint16",
	},
	{
		Type:     "uint32",
		TypeName: "Uint32",
	},
	{
		Type:     "uint64",
		TypeName: "Uint64",
	},
	{
		Type:     "int",
		TypeName: "Int",
	},
	{
		Type:     "int8",
		TypeName: "Int8",
	},
	{
		Type:     "int16",
		TypeName: "Int16",
	},
	{
		Type:     "int32",
		TypeName: "Int32",
	},
	{
		Type:     "int64",
		TypeName: "Int64",
	},
	{
		Type:     "float32",
		TypeName: "Float32",
	},
	{
		Type:     "float64",
		TypeName: "Float64",
	},
	{
		Type:     "byte",
		TypeName: "Byte",
	},
	{
		Type:     "rune",
		TypeName: "Rune",
	},
	{
		Type:     "uintptr",
		TypeName: "Uintptr",
	},
}
